version: "3.9"

services:
  go-elastic-board:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BUILD_VERSION: ${GIT_COMMIT:-dev}
        BUILD_TIME: ${BUILD_TIME:-local}
    image: go-elastic-board:latest
    container_name: go-elastic-board
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/etc/go-elastic-board/config.yaml:ro
      # Include the following comment if you want to mention certs too
      #- /path/to/certs:/path/to/certs
    # This lets the container reach an ES running on your HOST at 9200
    # (works on Linux with Docker >= 20.10 and on Docker Desktop)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

